apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - template-required-labels.yaml
  - constraint-required-labels.yaml
  - template-disallow-latest.yaml
  - constraint-disallow-latest.yaml
